apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-server
  namespace: fom-jchristmann
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nginx:latest
        ports:
          - containerPort: 80
            name: http-server
